const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./index.js']

const doc = {
    info: {
        version: "1.0.0",
        title: "MyGym BOT API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
   
}
    


swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./index.js')
})